services:
  speech-container:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: speech-container
    working_dir: /app
    volumes:
      - .:/app
    networks:
      - speech-network
    command: ["python", "server.py", "--port", "2224", "--whispermodel", "tiny"]
  caddy:
    image: caddy:latest
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
    ports:
      - 443:443
    networks:
      - speech-network
    depends_on:
      - speech-container

networks:
  speech-network:
    driver: bridge
