# Docker Compose configuration file for setting up a speech transcription service

services:
  # Service definition for the speech transcription container
  speech-container:
    # Build configuration for the container
    build:
      context: . # The build context is the current directory
      dockerfile: Dockerfile # The Dockerfile to use for building the image
    container_name: speech-container # Name of the container
    environment:
      - WHISPER_MODEL=${WHISPER_MODEL:-medium} # Set the WHISPER_MODEL environment variable to 'tiny'
      - WHISPER_PORT=2224 # Set the PORT environment variable to '2224'
      - WHISPER_HOST=${WHISPER_HOST:-0.0.0.0} # Set the HOST environment variable to '
    networks:
      - speech-network # Connect the container to the 'speech-network' network
    command: ["python", "server.py"] # Command to run when the container starts
    restart: on-failure # Restart policy on failure

  # Service definition for the Caddy reverse proxy
  caddy:
    container_name: caddy # Name of the container
    build:
      context: .
      dockerfile: Dockerfile.caddy
    ports:
      - ${WHISPER_PORT:-2224}:2224 # Map port 2224 on the host to port 443 on the container
    networks:
      - speech-network # Connect the container to the 'speech-network' network
    depends_on:
      - speech-container # Ensure the 'speech-container' service starts before this one
    restart: on-failure # Restart policy on failure

# Network configuration
networks:
  speech-network:
    driver: bridge # Use the bridge network driver
